### ISSUE TITLE
Define Reliability Goals

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/lira#112]
This ticket is for the purpose fo tracking the initial set of reliability goals for each component, reliability being defined as a combination of uptime and fault tolerance. Included would be tooling to track the state of each component and make measurements against the set goals.

**Comment by brianraymor** [comment]
Closing per Sam's decision on - https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/187
